cameras:
  - name: browser_cam
    url: browser
    fps: 15
    width: 1280
    height: 720
  - name: cam2
    url: rtsp://example.com/stream2
    fps: 15
    width: 1280
    height: 720
  - name: cam3
    url: rtsp://example.com/stream3
    fps: 15
    width: 1280
    height: 720
  - name: cam4
    url: rtsp://example.com/stream4
    fps: 15
    width: 1280
    height: 720
models:
  ensemble_name: multitask_ensemble
  detection_name: rtmdet_s
  segmentation_name: segformer
  depth_name: depth_fastdepth
  flow_name: optical_flow
  embedding_name: clip_encoder
